version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean package -Dmaven.test.skip

workflows:
  default:
    jobs:
      - build
